from email.message import EmailMessage
import smtplib

###############################################################
# @name                 : sendMail
#
# @description          : Sends an eMail to recipients. Senders
#                         eMail and password will be asked.
#
# @param usr_email      : eMail of sender
# @param pwd            : User password
# @param smtp_server    : SMTP server name
# @param smtp_port      : SMTP port number
# @param recipients     : a list of eMail address of recipients
# @param msg_subject    : Subject of the eMail
# @param msg_body       : Message body
###############################################################
def sendMail(
    usr_email,
    pwd,
    smtp_server,
    smtp_port,
    recipients,
    msg_subject,
    msg_body
    ):

    # Credentials
    #usr_email = raw_input("User eMail: ")
    #pwd = getpass.getpass()
    usr_email = usr_email.strip('"')
    user = usr_email

    # Sender and recipient
    fromaddr = usr_email
    toaddr = ', '.join(recipients)

    # Compose Message 
    msg = EmailMessage()
    msg['From'] = fromaddr
    msg['To'] = toaddr
    msg['Subject'] = msg_subject
    body = msg_body
    msg.set_content(body)

    print ("\nConnecting to: %s at Port: %d" % (smtp_server, smtp_port))
    server = smtplib.SMTP(smtp_server, smtp_port)

    server.ehlo()
    server.starttls()
    server.ehlo()

    # Login
    server.login(user, pwd)
    text = msg.as_string()

    # Send mail
    print ("Sending mail to: ", toaddr)
    server.sendmail(fromaddr, recipients, text)
    print (">> Sent")


##########################################################
# Send Mail
##########################################################

# Input parameters
usr_email = "sample@abc.com"
pwd = "dummyPassword"

# SMTP details
smtp_server = "sample_smtp_server.com"
smtp_port = 587

# Sender and receiver are same
recipients = [usr_email]

msg_subject = "Automated Mail"

msg_body = '''
This is an automated mail generated by Python module.

'''

sendMail(usr_email, pwd, smtp_server, smtp_port, recipients, msg_subject, msg_body)
